

export const GET_HOTLIST_SUCCESS = 'GET_HOTLIST_SUCCESS';
export const GET_NEWLIST_SUCCESS = 'GET_NEWLIST_SUCCESS';
export const GET_POPULARLIST_SUCCESS = 'GET_POPULARLIST_SUCCESS';
export const GET_TAG_LATEST_LIST_SUCCESS = 'GET_TAG_LATEST_LIST_SUCCESS';
export const GET_SEARCH_LIST_SUCCESS = 'GET_SEARCH_LIST_SUCCESS';


export const GET_SEARCH_LIST_PARAMS_SUCCESS = 'GET_SEARCH_LIST_PARAMS_SUCCESS';

export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';