

export const GET_HOTLIST_SUCCESS = 'GET_HOTLIST_SUCCESS';
export const GET_NEWLIST_SUCCESS = 'GET_NEWLIST_SUCCESS';
export const GET_POPULARLIST_SUCCESS = 'GET_POPULARLIST_SUCCESS';
export const GET_TAG_LATEST_LIST_SUCCESS = 'GET_TAG_LATEST_LIST_SUCCESS';
export const GET_SEARCH_LIST_SUCCESS = 'GET_SEARCH_LIST_SUCCESS';


export const GET_SEARCH_LIST_PARAMS_SUCCESS = 'GET_SEARCH_LIST_PARAMS_SUCCESS';

export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';

export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS';

export const GET_MIX_DETAIL_SUCCESS = 'GET_MIX_DETAIL_SUCCESS';


export const GET_MIX_LISTENERS_SUCCESS = 'GET_MIX_LISTENERS_SUCCESS';

export const GET_MIX_SIMILAR_SUCCESS = 'GET_MIX_SIMILAR_SUCCESS';

export const GET_MIX_FAVORITE_SUCCESS = 'GET_MIX_FAVORITE_SUCCESS';


export const GET_USER_PLAYLISTS_SUCCESS = 'GET_USER_PLAYLISTS_SUCCESS';
export const GET_USER_CLOUDCASTS_SUCCESS = 'GET_USER_CLOUDCASTS_SUCCESS';
export const GET_USER_FEED_SUCCESS = 'GET_USER_FEED_SUCCESS';


export const GET_TAG_DISCOVER_LIST_SUCCESS = 'GET_TAG_DISCOVER_LIST_SUCCESS';


export const GET_LOADING_STATUS = 'GET_LOADING_STATUS';